### ISSUE TITLE
defult @ApiParam name not set.

### ISSUE THREAD

**Issue by MS-Song** [martypitt/swagger-springmvc-example#11]
hi.

I love swagger :)

I use swagger 0.2.4.
Today upgrade version 0.3.0.
Very Good.

but 

```
        @ApiParam(value="useCache=true")
        @RequestParam(value="useCache",required=false) boolean useCache,
```

name is null

parameters: [
{
name: null,
defaultValue: "",
description: "useCache=true",
dataType: "boolean",
required: false,
allowableValues: null,
notes: "",
valueTypeInternal: null,
wrapperName: null,
internalDescription: null,
paramAccess: null,
allowMultiple: false,
paramType: "query"
},

0.2.4 
name: useCache

please help me

**Comment by dilipkrish** [comment]
This issue has been fixed in 0.3.1-SNAPSHOT build
