### ISSUE TITLE
stackoverflowerror for selfreferencing model object

### ISSUE THREAD

**Issue by suman291857** [martypitt/swagger-springmvc-example#16]
hello
I have a model object which i return from a response of a resource using @Responsebody annotation.
So the example project you can assume that Pet model object will have a reference to a List<Pet> pets;
When i invoke api-doc,i get stackoverflow error.
I tried with example-project and it results in the same problem.

Thanks

**Comment by dilipkrish** [comment]
I'll have to take a look. Do you have a fork I can take a look at?

**Comment by suman291857** [comment]
Hi,
Please have a look
https://github.com/suman291857/swagger-springmvc-example/blob/master/src/main/java/com/mangofactory/swagger/springmvc/example/PetService.java

I have added a new method called 

  @RequestMapping(value = "/newpets", method = RequestMethod.GET)
    @ApiOperation(value = "List all pets")
    public
    @ResponseBody
    NewPet listNewPets() {
        return new NewPet();
    }

If you hit
http://localhost:8080/swagger-springmvc-test/api-docs/pets
you can replicate the issue

Thanks

**Comment by dilipkrish** [comment]
@suman291857 Thanks for the example! This should be fixed 0.5.1
