### ISSUE TITLE
Adding the dependency breaks existing request mappings

### ISSUE THREAD

**Issue by ensonik** [martypitt/swagger-springmvc-example#22]
My project uses a hybrid of both XML and annotation based configuration (heavy on the XML).

Simply adding a dependency to the ivy configuration file breaks my application. It starts up error free, but none of the mappings work anymore. 

<dependency org="com.mangofactory" name="swagger-springmvc" rev="0.5.3"/>

There is likely some initializing bean of some sort that plays around with mappings, but I haven't figured out where it comes from.

As well, where do questions/feature requests get posted? As a new issue?

Thanks.

**Comment by dilipkrish** [comment]
@ensonik Not familiar with ivy configuration fire. As for posting feature requests/issues you're at the right place :)

**Comment by ensonik** [comment]
Hi Marty, the Ivy xml fragment I put there is the exact equivalent of a Maven dependency. Basically, I'm telling my dependency manager to bring in swagger-springmvc into my runtime classpath. 

Adding that dependency (without any actualy code or configuration changes to my project) is enough to break all my existing mappings.
