### ISSUE TITLE
Swagger UI is not working

### ISSUE THREAD

**Issue by vacuumn** [martypitt/swagger-springmvc-example#25]
I am trying to run Swagger UI(url http://localhost:8080/swagger-springmvc-test/usage/index.html) on branch "rel-0.6-java-config" and getting JS error:
`Uncaught TypeError: Cannot call method 'toLowerCase' of undefined swagger.js:381`

**Comment by dilipkrish** [comment]
@vacuumn I pushed an update with the 0.6.6 dependency. It should just work

**Comment by vacuumn** [comment]
Thank you, it works now.
