### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by CraigFoote** [martypitt/swagger-springmvc-example#27]
Hi Marty, I wonder if you can help me. I feel I'm getting close but I've yet to produce an api-docs folder. Firstly, am I correct in understanding my target folder should contain an api-docs folder somewhere and it gets read by the swagger-ui?

So... I'm using swagger-springmvc-0.8.3 from Maven Central (which brought in swagger-core_2.10-1.3.2). I've cloned swagger-springmvc-example at version 0.5.0-SNAPSHOT but it depends on swagger-springmvc-0.7.0 which I can't find. Do you have plans to modernize the example to use 0.8.3? It looks to me that some important API has been removed from 0.8.3, is that correct? Will it still somehow support @ApiModel and @ApiErrors? Would I be better off using 0.6.6?

I've tried hacking the example to work with 0.8.3 but ended up commenting out so much that it doesn't work. I'm wondering though if my project which I've converted to use swagger-springmvc-0.8.3 can be fixed.

I've added the properties file and the spring-context.xml entries that you have minus the DocumentationConfig and ExtensibleModule - are they required? I see nothing about swagger in the output of "mvn clean install -e" but lots in "mvn clean install -X" output, though only about copying swagger.properties to classes folder. Is there anything in particular I should be looking for?

If you'd prefer to communicate by email, my address is CraigFoote@gmail.com. Thanks for the work and the sharing!

Craig

**Comment by martypitt** [comment]
Hey Craig

I have been away from the Swagger project for quite some time, so not sure if I'm the best to answer your questions.  The amazing @dilipkrish has been leading the charge recently.

That said, I'm about to introduce swagger into a project, so will pop back after I have everything running, and see if I can answer your questions.  If it turns out this demo project needs updating, I'll do so.

However, it'll probably be early next week before I can answer your questions.

**Comment by CraigFoote** [comment]
Ok, thanks Marty.

**Comment by dilipkrish** [comment]
@craigfoote take a look at this project https://github.com/adrianbk/swagger-springmvc-demo

**Comment by CraigFoote** [comment]
Hi guys, thanks for the help. Unfortunately I do not use (or know) gradle so I'm not getting much from adrianbk's work. Dilip, your project seems to be using swagger-springmvc-0.3.0 and so doesn't support @ApiModel annotations, necessary for our project I think. I'd like to use the latest, 0.8.3, so I'm referring back to Marty's work again. I think I'm close. The DefaultSwaggerController is being called but is returning null because neither SwaggerApiResourceListing#initialize nor SwaggerCache#addSwaggerResourceListing are being called. I suspect a problem with my spring config entries:

```
<context:component-scan base-package="com.mangofactory.swagger.controllers"/>
<context:component-scan base-package="com.mangofactory.swagger.configuration"/>
<context:annotation-config/>
<mvc:default-servlet-handler/>
<context:property-placeholder location="classpath:swagger.properties"/>
```

Marty then has two beans declared from his test project, DocumentationConfig and CustomExtensibilityModule, but they don't compile with swagger-springmvc-0.8.3. I'm thinking I need to do something here rather than just comment out the beans. I'm just not sure what those beans are doing and if they really are required. I see it's annotated with @PostConstruct, what is supposed to call SwaggerApiResourceListing#initialize?

Any ideas?
Craig

**Comment by CraigFoote** [comment]
I just found that when I commented out this block in my spring config:

```
<mvc:annotation-driven>
  <mvc:message-converters>
    <bean class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
      <property name="prettyPrint" value="true"/>
    </bean>
  </mvc:message-converters>
</mvc:annotation-driven>
```

... that I get a startup error saying "error creating bean with name "springSwaggerConfig" because no bean was found to satisfy its "handlerMappings" autowired field, of type org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping". On a whim, I created a bean of that type but then just got a different error.

So two things:
1. Is "mvc:annotation-driven" not compatible with "context:annotation-config"?
2. Assuming I can find another way to declare pretty print that works with "mvc:annotation-driven", what handlerMapping should I be declaring?

Craig

**Comment by CraigFoote** [comment]
So the more I work on this the more I think my problem is that the SwaggerApiResourceListing#initialize, annotated with @PostConstruct, is not called even though I'm using:

```
<context:annotation-config/>
```

Any ideas why?
Craig

**Comment by CraigFoote** [comment]
So looking at http://java.dzone.com/articles/documenting-your-spring-api, I suspect my problem is not having SwaggerConfig and ApiPathProvider. I copied them into my project and they don't compile. Looking at https://github.com/martypitt/swagger-springmvc/issues/244 I see why. Do you have copies of these two files that do compile under swagger-springmvc-0.8.3? Specifically I'm wondering 
1. how to use swagger-models-0.8.3's Types for SwaggerGlobalSettings 
2. how to handle the missing and new methods in SwaggerPathProvider, implemented by ApiPathProvider

Once I get these classes compiling, am I correct in thinking the @Configuration annotation does not require any further spring config file entries?

Sorry for all the noise but thanks again for your help guys,
Craig

**Comment by dilipkrish** [comment]
@CraigFoote I feel it might be a good idea to start afresh using the 0.8.4-SNAPSHOT [instructions](https://github.com/martypitt/swagger-springmvc/blob/master/next-release.md) ... I dont think the answer is to copy files from older versions and force it to compile. 

Also unfortunately, the 0.8.x is a version thats a little bit hard to pin down as its a transition to a new implementation in addition to implementing the swagger 1.2 specification.

**Comment by CraigFoote** [comment]
Thanks Dilip, I've got things working with the snapshot and those instructions! Unfortunately we cannot use snapshots for our production systems. Do you have a release date planned for 0.8.4?

Craig

**Comment by dilipkrish** [comment]
Still working out a few issues before we release 0.8.4 as it forms the basis for the next release. Once its ironed out it should be out in a couple of weeks.

**Comment by CraigFoote** [comment]
Ok Dilip, I'll check back periodically. Thanks again for your help.

Craig
