### ISSUE TITLE
Could not build the example project due to dependency issue

### ISSUE THREAD

**Issue by karmarv** [martypitt/swagger-springmvc-example#28]
Error building in "mvn package install" command because of the repository not being available.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:39.205s
[INFO] Finished at: Sat May 24 15:00:06 IST 2014
[INFO] Final Memory: 7M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project swagger-springmvc-test: Could not resolve dependencies for project com.mangofactory.swagger:swagger-springmvc-test:war:0.5.0-SNAPSHOT: Cou
ld not find artifact com.mangofactory:swagger-springmvc:jar:0.7.0-SNAPSHOT in sonatype (https://oss.sonatype.org/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by obazoud** [comment]
same issue here.
Could you update this project with last swagger version ?

**Comment by dilipkrish** [comment]
This project  is now defunct. Please look at [the demo project](https://github.com/adrianbk/swagger-springmvc-demo) that's listed on the main library website.
