### ISSUE TITLE
Issue on RequestMapping with value like "/api/sample"

### ISSUE THREAD

**Issue by sdeleuze** [martypitt/swagger-springmvc-example#3]
Swagger SpringMVC integration works fine with path @RequestMapping(value = "/sample"), but not with @RequestMapping(value = "/api/sample")

Could you fix it or give me some hints in order to fix it ?

**Comment by Magua** [comment]
+1

**Comment by ened** [comment]
+1 Are there any updates on this?

**Comment by martypitt** [comment]
Migrated to https://github.com/martypitt/swagger-springmvc/issues/18
